version: '3.3'

services:
  pose-backend-service_flask:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=speechPose-d839583b988e.json
    container_name: flask
    expose:
      - 5000
    ports:
      - 5000:5000
    network_mode:
      host

  nginx:
    build:
        context: ../
        dockerfile: physio_flask_backend/nginx/Dockerfile
    container_name: nginx
    depends_on:
     - pose-backend-service_flask
    ports:
     -  8084:8084